<?php /** @var $block \Magento\GoogleAnalytics\Block\Ga */ ?>

<?php $_helper = $this->helper('Magento\GoogleAnalytics\Helper\Data') ?>

<?php if ($_helper->isGoogleAnalyticsAvailable()) : ?>
  <amp-analytics type="googleanalytics" id="analytics1">
    <script type="application/json">
      {
        "vars": {
          "account": "<?php echo $this->helper('Zemez\Amp\Helper\Data')->getGoogleAnalytics() ?>"
        },
        "triggers": {
          "trackPageview": {
            "on": "visible",
            "request": "pageview"
          }
        }
      }
    </script>
  </amp-analytics>

<amp-analytics type="googleanalytics" config="https://e-mosaictile.com/pub/media/ga4.json" data-credentials="include">
<script type="application/json">
{
    "vars": {
                "GA4_MEASUREMENT_ID": "G-6YN3asdf6",
                "GA4_ENDPOINT_HOSTNAME": "www.google-analytics.com",
                "DEFAULT_PAGEVIEW_ENABLED": true,    
                "GOOGLE_CONSENT_ENABLED": false,
                "WEBVITALS_TRACKING": false,
                "PERFORMANCE_TIMING_TRACKING": false,
                "SEND_DOUBLECLICK_BEACON": false
    }
}
</script>
</amp-analytics>
<?php endif; ?>
