({
    optimize: 'none',
    inlineText: true,
    deps: [
        'jquery/jquery.mobile.custom',
        'mage/common',
        'mage/dataPost',
        'mage/bootstrap',
        'jquery/jquery-migrate',
        'mage/translate-inline',
        "jquery",
        "jquery/jquery.mobile.custom",
        "mage/common",
        "mage/dataPost",
        "mage/bootstrap",
        "Magento_Theme/js/responsive"
    ],
    shim: {
        'jquery/jquery-migrate': ['jquery'],
        'jquery/jquery.hashchange': ['jquery', 'jquery/jquery-migrate'],
        'jquery/jstree/jquery.hotkeys': ['jquery'],
        'jquery/hover-intent': ['jquery'],
        'mage/adminhtml/backup': ['prototype'],
        'mage/captcha': ['prototype'],
        'mage/common': ['jquery'],
        'mage/new-gallery': ['jquery'],
        'mage/webapi': ['jquery'],
        'jquery/ui': ['jquery'],
        'MutationObserver': ['es6-collections'],
        'tinymce': {
            'exports': 'tinymce'
        },
        'moment': {
            'exports': 'moment'
        },
        'matchMedia': {
            'exports': 'mediaCheck'
        },
        'jquery/jquery-storageapi': {
            'deps': ['jquery/jquery.cookie']
        },
        paypalInContextExpressCheckout: {
            exports: 'paypal'
        },
        "mageplaza/core/jquery/popup": ["jquery"],
        "mageplaza/core/owl.carousel": ["jquery"],
        "mageplaza/core/bootstrap": ["jquery"],
        mpIonRangeSlider: ["jquery"],
        mpDevbridgeAutocomplete: ["jquery"],
        touchPunch: ['jquery', 'jquery/ui'],
        "blogOwlCarousel":  ["jquery"],
        "jquery.countdown": ["jquery"],
        "featuredOwlCarousel":  ["jquery"],
        "sliderInit": ["jquery"],
        "brandOwlCarousel":  ["jquery"],
        "jquery.countdown.sm": ["jquery"],
        "rdnavbar":         ["jquery"],
        "owlcarousel":      ["jquery"],
        "doubleTap":      ["jquery"],
        "animateNumber":    ["jquery"]
    },
    paths: {
        'jquery/ui': 'jquery/jquery-ui',
        'jquery/validate': 'jquery/jquery.validate',
        'jquery/hover-intent': 'jquery/jquery.hoverIntent',
        'jquery/file-uploader': 'jquery/fileUploader/jquery.fileupload-fp',
        'jquery/jquery.hashchange': 'jquery/jquery.ba-hashchange.min',
        'prototype': 'legacy-build.min',
        'jquery/jquery-storageapi': 'jquery/jquery.storageapi.min',
        'text': 'mage/requirejs/text',
        'domReady': 'requirejs/domReady',
        'tinymce': 'tiny_mce/tiny_mce_src',
        paypalInContextExpressCheckout: 'https://www.paypalobjects.com/api/checkout',
        'ui/template': 'Magento_Ui/templates',
        "productListingGallery": "TemplateMonster_ThemeOptions/js/product-listing-gallery",
        "switchImage": "TemplateMonster_ThemeOptions/js/switch-image",     
        'mageplaza/core/jquery/popup': 'Mageplaza_Core/js/jquery.magnific-popup.min',
        'mageplaza/core/owl.carousel': 'Mageplaza_Core/js/owl.carousel.min',
        'mageplaza/core/bootstrap': 'Mageplaza_Core/js/bootstrap.min',
        mpIonRangeSlider: 'Mageplaza_Core/js/ion.rangeSlider.min',
        touchPunch: 'Mageplaza_Core/js/jquery.ui.touch-punch.min',
        mpDevbridgeAutocomplete: 'Mageplaza_Core/js/jquery.autocomplete.min',
        temandoCheckoutFieldsDefinition: 'Temando_Shipping/js/model/fields-definition',
        temandoDeliveryOptions: 'Temando_Shipping/js/model/delivery-options',
        temandoShippingRatesValidator: 'Temando_Shipping/js/model/shipping-rates-validator/temando',
        temandoShippingRatesValidationRules: 'Temando_Shipping/js/model/shipping-rates-validation-rules/temando',
        priceRangeSlider: 'TemplateMonster_AjaxCatalog/js/tm-price-slider',        
        "blogCarousel":           "TemplateMonster_Blog/js/blog-carousel",
        "categoriesListCollapse": "TemplateMonster_Blog/js/categories-list-collapse",
        "blogOwlCarousel":        "TemplateMonster_Blog/js/owl.carousel",
        "featuredCarousel":       "TemplateMonster_FeaturedProduct/js/featured-carousel",
        "featuredTab":            "TemplateMonster_FeaturedProduct/js/featured-tab",
        "featuredOwlCarousel":    "TemplateMonster_FeaturedProduct/js/owl.carousel2",
        "featuredProductGallery": "TemplateMonster_FeaturedProduct/js/featured-product-gallery",
        "featuredSwitchImage":    "TemplateMonster_FeaturedProduct/js/featured-switch-image",
        sliderInit: 'TemplateMonster_FilmSlider/js/jquery.sliderPro',
        FilmSlider: 'TemplateMonster_FilmSlider/js/film-slider',
        "customizationTool": "TemplateMonster_LayoutSwitcher/js/customization-tool",
        "megamenu":        "TemplateMonster_Megamenu/js/megamenu",
        "subMenuViewMode": "TemplateMonster_Megamenu/js/subMenuViewMode",
        "carouselInit":     'js/carouselInit',
        "blockCollapse":    'js/sidebarCollapse',
        "animateNumber":    'js/jquery.animateNumber.min',
        "rdnavbar":         'Magento_Theme/js/jquery.rd-navbar',
        "owlcarousel":      'Magento_Theme/js/owl.carousel',
        "customSelect":     "Magento_Theme/js/select2",
        "doubleTap":        "Magento_Theme/js/doubletaptogo",
        "googleMapOptions": "js/googleMapOptions",
        "blogCarouselChild":           "TemplateMonster_Blog/js/blog-carouse-child",
        "featuredCarouselTheme":     "TemplateMonster_FeaturedProduct/js/featured-carousel-theme"
    },
    map: {
        '*': {
            'rowBuilder': 'Magento_Theme/js/row-builder',
            'toggleAdvanced': 'mage/toggle',
            'translateInline': 'mage/translate-inline',
            'sticky': 'mage/sticky',
            'tabs': 'mage/tabs',
            'zoom': 'mage/zoom',
            'collapsible': 'mage/collapsible',
            'dropdownDialog': 'mage/dropdown',
            'dropdown': 'mage/dropdowns',
            'accordion': 'mage/accordion',
            'loader': 'mage/loader',
            'tooltip': 'mage/tooltip',
            'deletableItem': 'mage/deletable-item',
            'itemTable': 'mage/item-table',
            'fieldsetControls': 'mage/fieldset-controls',
            'fieldsetResetControl': 'mage/fieldset-controls',
            'redirectUrl': 'mage/redirect-url',
            'loaderAjax': 'mage/loader',
            'menu': 'mage/menu',
            'popupWindow': 'mage/popup-window',
            'validation': 'mage/validation/validation',
            'welcome': 'Magento_Theme/js/view/welcome',
            'breadcrumbs': 'Magento_Theme/js/view/breadcrumbs',
            'ko': 'knockoutjs/knockout',
            'knockout': 'knockoutjs/knockout',
            'mageUtils': 'mage/utils/main',
            'rjsResolver': 'mage/requirejs/resolver',
            'checkoutBalance': 'Magento_Customer/js/checkout-balance',
            'address': 'Magento_Customer/address',
            'changeEmailPassword': 'Magento_Customer/change-email-password',
            'passwordStrengthIndicator': 'Magento_Customer/js/password-strength-indicator',
            'zxcvbn': 'Magento_Customer/js/zxcvbn',
            'addressValidation': 'Magento_Customer/js/addressValidation',
            'compareList': 'Magento_Catalog/js/list',
            'relatedProducts': 'Magento_Catalog/js/related-products',
            'upsellProducts': 'Magento_Catalog/js/upsell-products',
            'productListToolbarForm': 'Magento_Catalog/js/product/list/toolbar',
            'catalogGallery': 'Magento_Catalog/js/gallery',
            'priceBox': 'Magento_Catalog/js/price-box',
            'priceOptionDate': 'Magento_Catalog/js/price-option-date',
            'priceOptionFile': 'Magento_Catalog/js/price-option-file',
            'priceOptions': 'Magento_Catalog/js/price-options',
            'priceUtils': 'Magento_Catalog/js/price-utils',
            'catalogAddToCart': 'Magento_Catalog/js/catalog-add-to-cart',
            'creditCardType': 'Magento_Payment/cc-type',
            'quickSearch': 'Magento_Search/form-mini',
            'catalogSearch': 'Magento_CatalogSearch/form-mini',
            'giftMessage': 'Magento_Sales/gift-message',
            'ordersReturns': 'Magento_Sales/orders-returns',
            'discountCode': 'Magento_Checkout/js/discount-codes',
            'shoppingCart': 'Magento_Checkout/js/shopping-cart',
            'regionUpdater': 'Magento_Checkout/js/region-updater',
            'sidebar': 'Magento_Checkout/js/sidebar',
            'checkoutLoader': 'Magento_Checkout/js/checkout-loader',
            'checkoutData': 'Magento_Checkout/js/checkout-data',
            'proceedToCheckout': 'Magento_Checkout/js/proceed-to-checkout',
            'orderReview': 'Magento_Paypal/order-review',
            'paypalCheckout': 'Magento_Paypal/js/paypal-checkout',
            'transparent': 'Magento_Payment/transparent',
            'bundleOption': 'Magento_Bundle/bundle',
            'priceBundle': 'Magento_Bundle/js/price-bundle',
            'slide': 'Magento_Bundle/js/slide',
            'productSummary': 'Magento_Bundle/js/product-summary',
            'captcha': 'Magento_Captcha/captcha',
            'amazonLogout': 'Amazon_Login/js/amazon-logout',
            'amazonOAuthRedirect': 'Amazon_Login/js/amazon-redirect',
            'amazonCsrf': 'Amazon_Login/js/amazon-csrf',
            'amazonCore': 'Amazon_Payment/js/amazon-core',
            'amazonWidgetsLoader': 'Amazon_Payment/js/amazon-widgets-loader',
            'amazonButton': 'Amazon_Payment/js/amazon-button',
            'amazonProductAdd': 'Amazon_Payment/js/amazon-product-add',
            'bluebird': 'Amazon_Payment/js/lib/bluebird.min',
            'amazonPaymentConfig': 'Amazon_Payment/js/model/amazonPaymentConfig',
            'sjcl': 'Amazon_Payment/js/lib/sjcl.min',
            'addToCart': 'Magento_Msrp/js/msrp',
            'wishlist': 'Magento_Wishlist/js/wishlist',
            'addToWishlist': 'Magento_Wishlist/js/add-to-wishlist',
            'wishlistSearch': 'Magento_Wishlist/js/search',
            'transparent': 'Magento_Payment/transparent',
            'configurable': 'Magento_ConfigurableProduct/js/configurable',
            'requireCookie': 'Magento_Cookie/js/require-cookie',
            'cookieNotices': 'Magento_Cookie/js/notices',
            'downloadable': 'Magento_Downloadable/downloadable',
            'giftOptions': 'Magento_GiftMessage/gift-options',
            'extraOptions': 'Magento_GiftMessage/extra-options',
            'uiElement': 'Magento_Ui/js/lib/core/element/element',
            'uiCollection': 'Magento_Ui/js/lib/core/collection',
            'uiComponent': 'Magento_Ui/js/lib/core/collection',
            'uiClass': 'Magento_Ui/js/lib/core/class',
            'uiEvents': 'Magento_Ui/js/lib/core/events',
            'uiRegistry': 'Magento_Ui/js/lib/registry/registry',
            'consoleLogger': 'Magento_Ui/js/lib/logger/console-logger',
            'uiLayout': 'Magento_Ui/js/core/renderer/layout',
            'buttonAdapter': 'Magento_Ui/js/form/button-adapter',
            'multiShipping': 'Magento_Multishipping/js/multi-shipping',
            'orderOverview': 'Magento_Multishipping/js/overview',
            'payment': 'Magento_Multishipping/js/payment',
            'billingLoader': 'Magento_Checkout/js/checkout-loader',
            'cartUpdate': 'Magento_Checkout/js/action/update-shopping-cart',
            'pageCache': 'Magento_PageCache/js/page-cache',
            'Magento_Checkout/template/billing-address/form.html': 'Bss_OneStepCheckout/template/billing-address/form.html',
            'recentlyViewedProducts': 'Magento_Reports/js/recently-viewed',
            'loadPlayer': 'Magento_ProductVideo/js/load-player',
            'fotoramaVideoEvents': 'Magento_ProductVideo/js/fotorama-add-video-events',
            'klarnapi': 'https://x.klarnacdn.net/kp/lib/v1/api.js',
            'editTrigger': 'mage/edit-trigger',
            'addClass': 'Magento_Translation/add-class',
            'braintree': 'https://js.braintreegateway.com/js/braintree-2.32.0.min.js',
            'taxToggle': 'Magento_Weee/tax-toggle',
            'productListToolbarForm': 'TemplateMonster_AjaxCatalog/js/tm-catalog-ajax',
            'compareItems': 'TemplateMonster_AjaxCompare/js/tm-compare-ajax',
            'showCompareProduct': 'TemplateMonster_AjaxCompare/js/compare-products-top-link',
            'quickSearch': 'TemplateMonster_AjaxSearch/js/tm-search-ajax',
            'ajaxWishlist': 'TemplateMonster_AjaxWishlist/js/ajaxwishlist',
            'wishlist': 'TemplateMonster_AjaxWishlist/js/wishlist',
            'countdowntimer': 'TemplateMonster_CountdownTimer/js/countdowntimer',
            'jquery.countdown': 'TemplateMonster_CountdownTimer/js/jquery.countdown',
            'googleMapPagePlugin': 'TemplateMonster_GoogleMap/js/google-map-page-plugin',
            'brandAddProductPage': 'TemplateMonster_ShopByBrand/js/brand-add-product-page',
            'brandCarousel': 'TemplateMonster_ShopByBrand/js/brand-carousel',
            'brandOwlCarousel': 'TemplateMonster_ShopByBrand/js/owl.carousel',
            'smcountdowntimer': 'TemplateMonster_SiteMaintenance/js/countdowntimer',
            'jquery.countdown.sm': 'TemplateMonster_SiteMaintenance/js/jquery.countdown',
            'set-checkout-messages': 'Vertex_Tax/js/model/set-checkout-messages',
            'theme': 'js/theme',
            'themeChild': 'js/theme-child',
            'selectize': 'js/selectize',
            'googleMapOptions': 'js/googleMapOptions',
            'modalFilter': 'Magento_LayeredNavigation/js/modal-filter',
            'reviewRatingBehave': 'Magento_Review/js/reviewRating'
        },
    },
    
    modules: [
        {
            name: 'requirejs/require',
            include: [
                'mage/requirejs/mixins',
                'mage/common',
                'jquery/jquery.cookie',
                'jquery/jquery-storageapi',
                'jquery/jquery.mobile.custom',
                'jquery/jquery.hashchange',
                'jquery/ui',
            ],
            exclude: [
            ]
        },
        {
            name: 'mage/bootstrap',
            include: [
                'jquery',
                'knockoutjs/knockout',
                'mage/translate',
                'jquery/jquery-migrate',
                "jquery/jquery-ui-timepicker-addon",
                'mage/dataPost',
                'mage/translate-inline',
                'Magento_Theme/js/responsive',
                'Magento_Theme/js/theme',
                'text!ui/template/form/element/checkbox.html',
                'text!ui/template/form/element/date.html',
                'text!ui/template/form/element/helper/tooltip.html',
                'text!ui/template/form/element/textarea.html',
                'text!ui/template/group/group.html',
                'text!ui/template/form/element/input.html',
                'text!ui/template/form/element/select.html',
                'text!ui/template/form/field.html',
                'Magento_Ui/js/block-loader',
                'Magento_Ui/js/form/components/group',
                'Magento_Ui/js/form/element/boolean',
                'Magento_Ui/js/form/element/date',
                'Magento_Ui/js/form/element/post-code',
                'Magento_Ui/js/form/element/textarea',
                'Magento_Ui/js/form/element/abstract',
                'Magento_Ui/js/form/element/region',
                'Magento_Ui/js/form/element/select',
                'Magento_Ui/js/lib/validation/rules',
                'Magento_Ui/js/lib/validation/utils',
                'Magento_Ui/js/lib/validation/validator',
                'Magento_Ui/js/core/renderer/layout',
                'Magento_Ui/js/core/renderer/types',
                'Magento_Ui/js/form/adapter',
                'Magento_Ui/js/form/adapter/buttons',
                'Magento_Ui/js/lib/core/class',
                'Magento_Ui/js/lib/core/collection',
                'Magento_Ui/js/lib/core/element/element',
                'Magento_Ui/js/lib/core/element/links',
                'Magento_Ui/js/lib/core/events',
                'Magento_Ui/js/lib/core/storage/local',
                'Magento_Ui/js/lib/key-codes',
                'Magento_Ui/js/lib/knockout/bindings/after-render',
                'Magento_Ui/js/lib/knockout/bindings/autoselect',
                'Magento_Ui/js/lib/knockout/bindings/bind-html',
                'Magento_Ui/js/lib/knockout/bindings/bootstrap',
                'Magento_Ui/js/lib/knockout/bindings/collapsible',
                'Magento_Ui/js/lib/knockout/bindings/datepicker',
                'Magento_Ui/js/lib/knockout/bindings/fadeVisible',
                'Magento_Ui/js/lib/knockout/bindings/i18n',
                'Magento_Ui/js/lib/knockout/bindings/keyboard',
                'Magento_Ui/js/lib/knockout/bindings/mage-init',
                'Magento_Ui/js/lib/knockout/bindings/optgroup',
                'Magento_Ui/js/lib/knockout/bindings/outer_click',
                'Magento_Ui/js/lib/knockout/bindings/range',
                'Magento_Ui/js/lib/knockout/bindings/resizable',
                'Magento_Ui/js/lib/knockout/bindings/scope',
                'Magento_Ui/js/lib/knockout/bindings/simple-checked',
                'Magento_Ui/js/lib/knockout/bindings/staticChecked',
                'Magento_Ui/js/lib/knockout/bindings/tooltip',
                'Magento_Ui/js/lib/knockout/bootstrap',
                'Magento_Ui/js/lib/knockout/extender/bound-nodes',
                'Magento_Ui/js/lib/knockout/extender/observable_array',
                'Magento_Ui/js/lib/knockout/template/engine',
                'Magento_Ui/js/lib/knockout/template/loader',
                'Magento_Ui/js/lib/knockout/template/observable_source',
                'Magento_Ui/js/lib/knockout/template/renderer',
                'Magento_Ui/js/lib/logger/console-logger',
                'Magento_Ui/js/lib/logger/console-output-handler',
                'Magento_Ui/js/lib/logger/entry',
                'Magento_Ui/js/lib/logger/entry-factory',
                'Magento_Ui/js/lib/logger/formatter',
                'Magento_Ui/js/lib/logger/levels-pool',
                'Magento_Ui/js/lib/logger/logger',
                'Magento_Ui/js/lib/logger/logger-utils',
                'Magento_Ui/js/lib/logger/message-pool',
                'Magento_Ui/js/lib/registry/registry',
                'Magento_Ui/js/lib/spinner',
                'Magento_Ui/js/lib/view/utils/async',
                'Magento_Ui/js/lib/view/utils/bindings',
                'Magento_Ui/js/lib/view/utils/dom-observer',
                'Magento_Ui/js/modal/alert',
                'Magento_Ui/js/modal/confirm',
                'Magento_Ui/js/modal/modal',
                'Magento_Ui/js/model/messageList',
                'Magento_Ui/js/model/messages'
            ],
            exclude: [
                'requirejs/require',
            ]
        },
        {
            name: 'bundles/default',
            create: true,
            include: [
                'mage/requirejs/resolver',
                'mage/smart-keyboard-handler',
                'mage/storage',
                'mage/tabs',
                'mage/template',
                'mage/translate',
                'mage/translate-inline',
                'mage/url',
                'mage/utils/arrays',
                'mage/utils/compare',
                'mage/utils/main',
                'mage/utils/misc',
                'mage/utils/objects',
                'mage/utils/strings',
                'mage/utils/template',
                'mage/utils/wrapper',
                'mage/validation',
                'mage/apply/main',
                'mage/apply/scripts',
                'mage/bootstrap',
                'mage/calendar',
                'mage/collapsible',
                'mage/common',
                'mage/cookies',
                'mage/dataPost',
                'mage/decorate',
                'mage/dropdown',
                'mage/dropdowns',
                'mage/ie-class-fixer',
                'mage/loader',
                'mage/mage',
                'matchMedia',
                'mixins',
                'moment',
                'MutationObserver',
                'owlcarousel',
                'rdnavbar',
                'underscore',
                'Amazon_Login/js/view/login-button-wrapper',
                'animateNumber',
                'blockCollapse',
                'Bss_MultiStoreViewPricing/js/view/minicart',
                'Bss_ProductLabel/js/label',
                'carouselInit',
                'customSelect',
                'domReady',
                'doubleTap',
                'es6-collections',
                'FormData',
                'googleMapOptions',
                'selectize',
                'js/theme',
                'js/theme-child',
                'knockoutjs/knockout',
                'knockoutjs/knockout-es5',
                'knockoutjs/knockout-fast-foreach',
                'knockoutjs/knockout-repeat',
                'Magento_Captcha/js/action/refresh',
                'Magento_Captcha/js/model/captcha',
                'Magento_Captcha/js/model/captchaList',
                'Magento_Captcha/js/view/checkout/defaultCaptcha',
                'Magento_Captcha/js/view/checkout/loginCaptcha',
                'Magento_Catalog/js/catalog-add-to-cart',
                'Magento_Catalog/js/product/query-builder',
                'Magento_Catalog/js/product/storage/data-storage',
                'Magento_Catalog/js/product/storage/ids-storage',
                'Magento_Catalog/js/product/storage/ids-storage-compare',
                'Magento_Catalog/js/product/storage/storage-service',
                'Magento_Catalog/js/storage-manager',
                'Magento_Catalog/js/view/compare-products',
                'Magento_Catalog/js/view/image',
                'Magento_Checkout/js/sidebar',
                'Magento_Checkout/js/sidebar-mixin',
                'Magento_Checkout/js/view/minicart',
                'Magento_Checkout/js/view/minicart-extend',
                'Magento_Customer/js/action/login',
                'Magento_Customer/js/customer-data',
                'Magento_Customer/js/invalidation-processor',
                'Magento_Customer/js/invalidation-rules/website-rule',
                'Magento_Customer/js/model/authentication-popup',
                'Magento_Customer/js/section-config',
                'Magento_Customer/js/view/authentication-popup',
                'Magento_Customer/js/view/customer',
                'Magento_Msrp/js/view/checkout/minicart/subtotal/totals',
                'Magento_PageCache/js/page-cache',
                'Magento_Search/form-mini',
                'Magento_Tax/js/view/checkout/minicart/subtotal/totals',
                'Magento_Theme/js/device.min',
                'Magento_Theme/js/responsive',
                'Magento_Wishlist/js/view/wishlist',
                'TemplateMonster_AjaxCompare/js/compare-products-top-link',
                'TemplateMonster_AjaxSearch/js/tm-search-ajax',
                'TemplateMonster_AjaxWishlist/js/ajaxwishlist',
                'TemplateMonster_GoogleMap/js/google-map-page-plugin',
                'text!Magento_Captcha/template/checkout/captcha.html',
                'text!Magento_Checkout/template/minicart/content.html',
                'text!Magento_Customer/template/authentication-popup.html',
                'text!TemplateMonster_GoogleMap/templates/plugin.html',
                'mage/validation/validation',
                'mage/trim-input',
                'mage/redirect-url',
                'Magento_Customer/js/zxcvbn',
                'Magento_Customer/js/password-strength-indicator',
                'wishlist',
                'featuredOwlCarousel',
                'Magento_Wishlist/js/wishlist',
                'FilmSlider',
                'sliderInit',
                'blogOwlCarousel',
                'featuredCarouselTheme',
                'blogCarousel',
                'featuredCarousel'
            ],
            exclude: [
                'requirejs/require',
            ],
        },
        {
            name: 'bundles/cart',
            create: true,
            include: [
                'text!Magento_Tax/template/checkout/cart/totals/shipping.html',
                'Magento_Checkout/js/model/cart/estimate-service',
                'Magento_Fedex/js/model/shipping-rates-validation-rules',
                'Magento_OfflineShipping/js/model/shipping-rates-validation-rules/tablerate',
                'Magento_Fedex/js/view/shipping-rates-validation',
                'text!Magento_Checkout/template/cart/totals.html',
                'Magento_Dhl/js/model/shipping-rates-validator',
                'Magento_Dhl/js/model/shipping-rates-validation-rules',
                'Magento_Checkout/js/proceed-to-checkout',
                'Magento_Tax/js/view/checkout/cart/totals/shipping',
                'Magento_Tax/js/view/checkout/cart/totals/tax',
                'Magento_Ups/js/model/shipping-rates-validator',
                'Magento_GiftMessage/js/model/url-builder',
                'text!Magento_GiftMessage/template/gift-message-item-level.html',
                'Magento_Checkout/js/view/cart/totals',
                'Magento_Weee/js/view/cart/totals/weee',
                'Magento_Tax/js/view/checkout/cart/totals/grand-total',
                'Magento_Checkout/js/view/cart/shipping-rates',
                'Magento_OfflineShipping/js/model/shipping-rates-validator/freeshipping',
                'Magento_Checkout/js/model/cart/totals-processor/default',
                'Magento_Checkout/js/action/update-shopping-cart',
                'Magento_Checkout/js/shopping-cart',
                'Magento_GiftMessage/js/model/gift-message',
                'Magento_Checkout/js/model/cart/cache',
                'Magento_OfflineShipping/js/view/shipping-rates-validation/tablerate',
                'Magento_Dhl/js/view/shipping-rates-validation',
                'Magento_GiftMessage/js/view/gift-message',
                'Magento_Usps/js/model/shipping-rates-validator',
                'Magento_Usps/js/model/shipping-rates-validation-rules',
                'Magento_Fedex/js/model/shipping-rates-validator',
                'Magento_OfflineShipping/js/view/shipping-rates-validation/freeshipping',
                'mage/sticky',
                'text!Magento_Checkout/template/cart/shipping-estimation.html',
                'Magento_Ups/js/view/shipping-rates-validation',
                'text!Magento_Checkout/template/cart/shipping-rates.html',
                'text!Magento_Tax/template/checkout/cart/totals/grand-total.html',
                'Magento_OfflineShipping/js/model/shipping-rates-validation-rules/freeshipping',
                'text!Magento_Tax/template/checkout/cart/totals/tax.html',
                'text!Magento_GiftMessage/template/gift-message.html',
                'Magento_Ups/js/model/shipping-rates-validation-rules',
                'Magento_GiftMessage/js/model/gift-options',
                'Magento_Checkout/js/view/cart/shipping-estimation',
                'Magento_OfflineShipping/js/model/shipping-rates-validator/tablerate',
                'text!Magento_SalesRule/template/cart/totals/discount.html',
                'Magento_GiftMessage/js/action/gift-options',
                'Magento_Usps/js/view/shipping-rates-validation',
                'Magento_SalesRule/js/view/cart/totals/discount',
                'text!Magento_Checkout/template/minicart/item/price.html',
                'text!Bss_ProductLabel/template/minicart/item/default.html',
                'text!Magento_Catalog/template/product/image_with_borders.html',
                'text!Magento_Checkout/template/minicart/subtotal.html',
                'text!Magento_Tax/template/checkout/minicart/subtotal/totals.html'
            ],
            exclude: [
                'bundles/default',
                'bundles/catalog',
                'requirejs/require',
                'bundles/shipping',
                'mage/bootstrap',
            ],
        },
        {
            name: 'bundles/shipping',
            create: true,
            include: [
                'Magento_Tax/js/view/checkout/summary/tax',
                'Magento_Checkout/js/model/url-builder',
                'Magento_Checkout/js/model/checkout-data-resolver',
                'Magento_Checkout/js/action/create-billing-address',
                'Magento_Customer/js/model/customer-addresses',
                'Magento_Checkout/js/action/select-payment-method',
                'Bss_OneStepCheckout/js/model/step-navigator-mixin',
                'Magento_Checkout/js/model/default-validation-rules',
                'Magento_Checkout/js/view/summary/abstract-total',
                'Magento_Checkout/js/action/create-shipping-address',
                'Magento_Tax/js/view/checkout/shipping_method/price',
                'Magento_SalesRule/js/view/summary/discount',
                'Magento_Ui/js/form/element/abstract',
                'Magento_Checkout/js/checkout-data',
                'Magento_Checkout/js/view/summary/shipping',
                'Magento_Checkout/js/model/shipping-rates-validator',
                'Magento_Ui/js/form/element/select',
                'Magento_Checkout/js/model/default-validator',
                'text!Magento_Weee/template/checkout/summary/weee.html',
                'Magento_Checkout/js/model/shipping-rates-validation-rules',
                'text!ui/template/form/element/input.html',
                'Magento_Checkout/js/model/error-processor',
                'Magento_OfflineShipping/js/model/shipping-rates-validation-rules/flatrate',
                'Magento_Tax/js/view/checkout/summary/subtotal',
                'Magento_Checkout/js/model/postcode-validator',
                'text!Magento_Tax/template/checkout/summary/subtotal.html',
                'Magento_Checkout/js/model/new-customer-address',
                'Magento_Customer/js/model/customer/address',
                'Magento_Customer/js/model/address-list',
                'Magento_Checkout/js/model/payment-service',
                'Magento_Checkout/js/model/shipping-rate-processor/new-address',
                'Magento_Checkout/js/model/quote',
                'Magento_Checkout/js/model/shipping-address/form-popup-state',
                'Magento_Tax/js/view/checkout/summary/shipping',
                'text!ui/template/form/field.html',
                'Magento_Ui/js/lib/validation/utils',
                'Magento_Weee/js/view/checkout/summary/weee',
                'Magento_Checkout/js/action/select-shipping-address',
                'Magento_Customer/js/model/customer',
                'Magento_Checkout/js/model/default-post-code-resolver',
                'Magento_Ui/js/form/element/region',
                'Magento_Checkout/js/model/payment/method-list',
                'Magento_Checkout/js/model/totals',
                'Magento_Checkout/js/model/shipping-service',
                'text!ui/template/form/element/select.html',
                'Magento_Ui/js/lib/validation/rules',
                'Magento_Ui/js/lib/validation/validator',
                'Magento_Checkout/js/model/address-converter',
                'Magento_Checkout/js/action/select-billing-address',
                'Magento_Tax/js/view/checkout/summary/grand-total',
                'Magento_Checkout/js/model/shipping-rate-registry',
                'Magento_Checkout/js/model/resource-url-manager',
                'Magento_OfflineShipping/js/view/shipping-rates-validation/flatrate',
                'Magento_Checkout/js/action/select-shipping-method',
                'Magento_Checkout/js/model/step-navigator',
                'Magento_OfflineShipping/js/model/shipping-rates-validator/flatrate'
            ],
            exclude: [
                'bundles/default',
                'bundles/catalog',
                'bundles/checkout',
                'bundles/cart',
                'requirejs/require',
                'mage/bootstrap',
            ],
        },
        {
            name: 'bundles/checkout',
            create: true,
            include: [
                'moment-timezone-with-data',
                'Magento_SalesRule/js/view/payment/discount',
                'Magento_Weee/js/view/checkout/summary/item/price/row_excl_tax',
                'text!Bss_OneStepCheckout/template/summary/item/details.html',
                'Bss_OneStepCheckout/js/model/default-validation-rules',
                'Magento_Checkout/js/view/summary/totals',
                'Magento_Ui/js/form/components/group',
                'text!Magento_Tax/template/checkout/summary/grand-total.html',
                'Magento_Checkout/js/view/shipping-address/list',
                'Magento_OfflinePayments/js/view/payment/offline-payments',
                'text!Bss_OneStepCheckout/template/payment-methods/list.html',
                'Bss_OneStepCheckout/js/model/default-validator',
                'Magento_Checkout/js/view/sidebar',
                'Magento_Checkout/js/model/full-screen-loader',
                'text!ui/template/form/element/helper/tooltip.html',
                'Magento_Checkout/js/action/get-payment-information',
                'Magento_Tax/js/view/checkout/summary/item/details/subtotal',
                'text!ui/template/form/element/date.html',
                'Magento_Checkout/js/view/form/element/email',
                'text!Magento_Checkout/template/onepage.html',
                'Magento_CheckoutAgreements/js/view/checkout-agreements',
                'Magento_Checkout/js/view/summary/item/details/thumbnail',
                'Magento_Checkout/js/view/payment/list',
                'Bss_OneStepCheckout/js/model/url-builder',
                'Bss_OneStepCheckout/js/model/shipping-rates-validator',
                'Magento_Checkout/js/action/set-shipping-information',
                'Bss_OneStepCheckout/js/model/step-navigator',
                'Magento_Ui/js/form/element/post-code',
                'Magento_Checkout/js/view/authentication',
                'Magento_Customer/js/action/check-email-availability',
                'Magento_Checkout/js/model/payment/additional-validators',
                'text!Magento_Tax/template/checkout/summary/tax.html',
                'Bss_OneStepCheckout/js/model/shipping-save-processor/payload-extender',
                'text!Bss_OneStepCheckout/template/checkout/checkout-agreements.html',
                'Bss_OneStepCheckout/js/view/agreement-validation',
                'Bss_OneStepCheckout/js/model/shipping-save-processor/default',
                'text!Bss_OneStepCheckout/template/payment.html',
                'Magento_Checkout/js/model/payment/method-group',
                'Magento_Checkout/js/view/summary/item/details',
                'text!Magento_Checkout/template/shipping.html',
                'Magento_Checkout/js/view/estimation',
                'Magento_Checkout/js/model/payment/renderer-list',
                'Magento_Checkout/js/view/authentication-messages',
                'Magento_Checkout/js/model/shipping-save-processor/default',
                'Bss_OneStepCheckout/js/view/shipping',
                'text!Bss_OneStepCheckout/template/form/order-comment.html',
                'Magento_Checkout/js/view/summary',
                'Magento_Checkout/js/model/customer-email-validator',
                'text!Magento_Checkout/template/summary/cart-items.html',
                'Klarna_Kp/js/action/override',
                'Magento_SalesRule/js/action/set-coupon-code',
                'Bss_OneStepCheckout/js/view/payment/list',
                'Magento_Shipping/js/view/checkout/shipping/shipping-policy',
                'Bss_OneStepCheckout/js/view/payment',
                'text!Magento_Checkout/template/authentication.html',
                'Magento_Ui/js/form/element/date',
                'Bss_OneStepCheckout/js/view/billing-address',
                'text!Magento_Shipping/template/checkout/shipping/shipping-policy.html',
                'Magento_SalesRule/js/view/payment/discount-messages',
                'Bss_OneStepCheckout/js/model/agreement-validator',
                'Magento_Checkout/js/model/shipping-rate-service',
                'Magento_CheckoutAgreements/js/model/agreements-modal',
                'Bss_OneStepCheckout/js/view/shipping-address/list',
                'text!ui/template/form/element/checkbox.html',
                'Magento_SalesRule/js/model/payment/discount-messages',
                'Magento_Ui/js/form/element/textarea',
                'Magento_Paypal/js/view/payment/paypal-payments',
                'Magento_Ui/js/form/element/boolean',
                'text!Magento_Tax/template/checkout/summary/shipping.html',
                'Magento_Checkout/js/view/summary/cart-items',
                'text!Bss_OneStepCheckout/template/payment/discount.html',
                'Bss_OneStepCheckout/js/model/payment-service-default',
                'Magento_Checkout/js/model/shipping-rate-processor/customer-address',
                'text!Bss_OneStepCheckout/template/place-order-btn.html',
                'Magento_Checkout/js/model/payment/method-converter',
                'Magento_Checkout/js/model/shipping-save-processor',
                'Bss_OneStepCheckout/js/model/update-item-service',
                'Magento_Checkout/js/checkout-loader',
                'Bss_OneStepCheckout/js/view/place-order-btn',
                'Bss_OneStepCheckout/js/model/place-order-btn-service',
                'text!Magento_SalesRule/template/summary/discount.html',
                'Magento_Weee/js/view/checkout/summary/item/price/row_incl_tax',
                'Magento_SalesRule/js/action/cancel-coupon',
                'Bss_OneStepCheckout/js/model/shipping-save-processor',
                'text!Magento_Checkout/template/form/element/email.html',
                'Bss_OneStepCheckout/js/model/payment-service',
                'Bss_OneStepCheckout/js/action/update-item',
                'text!Magento_Checkout/template/summary/totals.html',
                'Klarna_Kp/js/model/config',
                'Magento_Checkout/js/view/summary/item/details/subtotal',
                'text!ui/template/group/group.html',
                'text!ui/template/form/element/textarea.html',
                'Magento_Checkout/js/model/shipping-save-processor/payload-extender',
                'Magento_Checkout/js/view/payment/email-validator',
                'Magento_Weee/js/view/checkout/summary/item/price/weee',
                'text!Magento_Checkout/template/estimation.html',
                'Magento_Shipping/js/model/config',
                'Bss_OneStepCheckout/js/view/form/element/email',
                'Bss_OneStepCheckout/js/view/onepage',
                'Bss_OneStepCheckout/js/view/summary/item/details',
                'text!Bss_OneStepCheckout/template/sidebar.html',
                'Magento_Payment/js/view/payment/payments',
                'text!Magento_Checkout/template/shipping-address/list.html',
                'Bss_OneStepCheckout/js/action/set-shipping-information',
                'Magento_Checkout/js/model/sidebar',
                'text!Magento_Checkout/template/shipping-address/form.html',
                'Magento_Checkout/js/model/authentication-messages',
                'text!Magento_Checkout/template/summary.html',
                'Magento_Checkout/js/action/set-billing-address',
                'priceUtils'
            ],
            exclude: [
                'bundles/default',
                'requirejs/require',
                'bundles/shipping',
                'mage/bootstrap',
            ],
        },
        {
            name: 'bundles/catalog',
            create: true,
            include: [
                'magnifier/magnify',
                'Magento_Catalog/js/upsell-products',
                'Magento_Catalog/js/validate-product',
                'Magento_Review/js/view/review',
                'Magento_ProductVideo/js/load-player',
                'text!Magento_InstantPurchase/template/instant-purchase.html',
                'Magento_Review/js/error-placement',
                'jquery/jquery.parsequery',
                'Magento_Catalog/js/product/view/provider',
                'Bss_PriceCustomize/js/mixins/swatch-renderer',
                'mage/gallery/gallery',
                'Magento_InstantPurchase/js/view/instant-purchase',
                'text!mage/gallery/gallery.html',
                'Magento_Review/js/validate-review',
                'Magento_ProductVideo/js/fotorama-add-video-events',
                'fotorama/fotorama',
                'Bss_ProductLabel/js/label-product-page',
                'Magento_Catalog/product/view/validation',
                'Magento_Catalog/js/gallery',
                'magnifier/magnifier',
                'text!Magento_InstantPurchase/template/confirmation.html',
                'Magento_Swatches/js/configurable-customer-data',
                'Magento_Catalog/js/price-box',
                'Magento_ConfigurableProduct/js/options-updater',
                'Magento_Swatches/js/swatch-renderer',
                'Magento_Review/js/process-reviews',
                'Magento_Review/js/review-rating',
                'switchImage',
                'Magento_LayeredNavigation/js/modal-filter',
                'Bss_ProductLabel/js/label-category-page',
                'mage/accordion'
            ],
            exclude: [
                'requirejs/require',
                'bundles/default',
                'mage/bootstrap'
            ],
        }
    ],
})