<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_RichSnippets
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2016 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
$helper = $block->getHelper();
$getEnableModule = $helper->getEnable();
$getEnable = $helper->getEnableForProduct();
$getEnableTwitter = $helper->getEnableForProductT();
$twitterUser = $helper->getTwitterUser();

$layoutFactory = $block->getLayoutFactory();

if(isset($layoutFactory->getMetadata()['description'])) {
    $description = $layoutFactory->getMetadata()['description'];
} else {
    $description = $block->getProduct()->getShortDescription();
}


?>
<?php if ($getEnableModule == '1'): ?>
	<?php
    if ($getEnable == '1'): ?>
        <meta property="og:type" content="og:product" />
        <meta property="og:title" content="<?php echo $block->escapeHtml($block->getProduct()->getName()); ?>" />
        <meta property="og:image" content="<?php echo $block->escapeUrl(
                $block->getImage($block->getProduct(), 'product_base_image'
            )->getImageUrl()); ?>" />
        <meta property="og:description" content="<?php echo $block->escapeHtml(
                $description); ?>" />
        <meta property="og:url" content="<?php echo $block->escapeUrl($block->getProduct()->getProductUrl()); ?>" />

	<?php
    endif; ?>
	<?php
    if ($getEnableTwitter == '1'): ?>
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:site" content="<?php echo $block->escapeUrl($twitterUser); ?>" />
        <meta name="twitter:title" content="<?php echo $block->escapeHtml($block->getProduct()->getName()); ?>" />
        <meta name="twitter:description" content="<?php echo $block->escapeHtml(
                $description); ?>" />
        <meta name="twitter:image" content="<?php echo $block->escapeUrl(
                $block->getImage($block->getProduct(), 'product_base_image')->getImageUrl()); ?>" />

	<?php
    endif; ?>
	<?php
    if ($priceAmount = $block->getProduct()->getFinalPrice()):?>
        <meta property="product:price:amount" content="<?php /* @escapeNotVerified */ echo $priceAmount; ?>"/>
	    <?php echo $block->getChildHtml('meta.currency'); ?>
	<?php
    endif; ?>
    <?php
else: ?>
        <meta property="og:type" content="og:product" />
        <meta property="og:title" content="<?php echo $block->escapeHtml($block->getProduct()->getName()); ?>" />
        <meta property="og:image" content="<?php echo $block->escapeUrl(
                $block->getImage($block->getProduct(), 'product_base_image')->getImageUrl()); ?>" />
        <meta property="og:description" content="<?php echo $block->escapeHtml(
                $block->getProduct()->getShortDescription()); ?>" />
        <meta property="og:url" content="<?php echo $block->escapeUrl($block->getProduct()->getProductUrl()); ?>" />
        <?php
    if ($priceAmount = $block->getProduct()->getFinalPrice()):?>
            <meta property="product:price:amount" content="<?php /* @escapeNotVerified */ echo $priceAmount; ?>"/>
            <?php echo $block->getChildHtml('meta.currency'); ?>
        <?php
    endif;?>
    <?php
endif;