<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_RichSnippets
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2016 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>

<?php
$myHelper = $block->getHelper();
$enable = $myHelper->getEnable();
?>
<?php $url = $block->getReviewsUrl() . '#reviews'; ?>
<?php $urlForm = $block->getReviewsUrl() . '#review-form'; ?>
<?php if ($block->getReviewsCount()): ?>
    <?php $rating = $block->getRatingSummary(); ?>
    <?php
    if ($enable == '0') : ?>

        <div class="product-reviews-summary<?php
        echo !$rating ? ' no-rating' : ''?>"
             itemprop="aggregateRating"
             itemscope itemtype="http://schema.org/AggregateRating">
    <?php
    else: ?>
        <div class="product-reviews-summary<?php echo !$rating ? ' no-rating' : ''?>">
    <?php
    endif; ?>
    <?php
    if ($rating):?>
        <div class="rating-summary">
             <span class="label"><span><?php echo __('Rating') ?>:</span></span>
             <div class="rating-result" title="<?php echo $rating; ?>%">
                 <span style="width:<?php echo $rating; ?>%"><span><span itemprop="ratingValue">
                         <?php echo $rating; ?>
                         </span><?php /* @escapeNotVerified */ echo __('% of') ?> <span itemprop="bestRating">100</span></span></span>
             </div>
         </div>
    <?php
    endif;?>
    <div class="reviews-actions">
        <a class="action view" href="<?php echo $url ?>"><span itemprop="reviewCount">
                <?php echo $block->getReviewsCount() ?></span>&nbsp;<span><?php echo($block->getReviewsCount() == 1) ? __('Review') : __('Reviews') ?></span></a>
        <a class="action add" href="<?php echo $urlForm ?>"><?php echo __('Add Your Review') ?></a>
    </div>
    </div>
    <?php
elseif ($block->getDisplayIfEmpty()): ?>
    <div class="product-reviews-summary empty">
        <div class="reviews-actions">
            <a class="action add" href="<?php /* @escapeNotVerified */ echo $urlForm; ?>">
                <?php /* @escapeNotVerified */ echo __('Be the first to review this product') ?>
            </a>
        </div>
    </div>
    <?php
endif;
