<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_DeferJS
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/** @var $block \Bss\DeferJs\Block\Table */
$module = $block->getModuleName();
$controller = $block->getControllerName();
$action = $block->getActionName();
$path = $module.'_'.$controller.'_'.$action;
?>
<?php // @codingStandardsIgnoreFile ?>
<table id="bss-table" cellspacing="0" cellpadding="2" border="1" style="width:auto;background-color:white">
    <tbody>
    <tr>
        <th>Controllers</th>
        <th>Path</th>
    </tr>
    <tr>
        <td align="left"><?php echo $block->escapeHtml($path) ?></td>
        <td align="right"><?php echo $block->escapeHtml($block->getRequestUri()) ?></td>
    </tr>
    </tbody>
</table>
<script type="text/x-magento-init">
{"*":{"Bss_DeferJS/js/move-table":{}}}
</script>