<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_ProductLabel
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php $selectorProduct = $block->getSelectorProduct();
$selectorProductList = $block->getSelectorProductList();
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Bss_ProductLabel/js/label-product-page":{
            	<?php if (!empty($selectorProduct)): ?>
            		"selector" : "<?php echo $selectorProduct; ?>"
            	<?php endif; ?>
            	<?php if (!empty($selectorProduct) && !empty($selectorProductList)): ?>
            		,
            	<?php endif; ?>
            	<?php if (!empty($selectorProductList)): ?>
            		"selectorProductList" : "<?php echo $selectorProductList; ?>"
            	<?php endif; ?>
        	}
        }
    }
</script>